/* VGA configuration */
#define VGA_WIDTH 80
#define VGA_HEIGHT 25
#define VGA_MEMORY 0xB8000

/* IDT */
#define IDT_MAX_DESCRIPTORS 256
#define PIC1_COMMAND_PORT 0X20
#define PIC1_DATA_PORT 0X21
#define PIC2_COMMAND_PORT 0XA0
#define PIC2_DATA_PORT 0XA1
#define IDT_INTERRUPT_GATE_32BIT 0x8E
#define IDT_INTERRUPT_GATE_USER 0xEE

/* Keyboard */
#define KEYBOARD_DATA_PORT 0x60
#define KEYBOARD_STATUS_PORT 0x64